
POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 100
}

####

GET http://localhost:8080/products/9a7670bb-f9bb-4639-87b2-231aafa51a5a
Content-Type: application/json

####

PUT http://localhost:8080/products/9a7670bb-f9bb-4639-87b2-231aafa51a5a
Content-Type: application/json

{
  "name": "Product 1 updated",
  "price": 200
}


####

DELETE http://localhost:8080/products/9a7670bb-f9bb-4639-87b2-231aafa51a5a
Content-Type: application/json


###

GET http://localhost:8080/products?page=2&limit=10&sort=asc
Content-Type: application/json