

  @token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDY3MTMxMTAsInN1YiI6ImFjMjI0ZTMwLTMxOTQtNGM3ZS05ZTQ4LTgwOGFkMTNjZDA2ZCJ9.Yax5FOLE1GwN8GMx-OYCYpCF_6OXysox3x4krg-CXJ0"


POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Product 1",
  "price": 100
}

####

GET http://localhost:8080/products/9a7670bb-f9bb-4639-87b2-231aafa51a5a
Content-Type: application/json

####

PUT http://localhost:8080/products/9a7670bb-f9bb-4639-87b2-231aafa51a5a
Content-Type: application/json

{
  "name": "Product 1 updated",
  "price": 200
}


####

DELETE http://localhost:8080/products/9a7670bb-f9bb-4639-87b2-231aafa51a5a
Content-Type: application/json


###

GET http://localhost:8080/products?page=1&limit=10&sort=asc
Authorization: Bearer {{token}}
Content-Type: application/json